name: servant-api

ghc-options: -Wall

library:
  source-dirs:
    - src

executables:
  example-servant-minimal:
    main: app/Main.hs
    dependencies:
      - servant-api

dependencies:
  - base
  - servant
  - servant-server
  - transformers
  - aeson
  - wai
  - warp
